
POST http://localhost:5000/eventos
Content-Type: application/json

{
    "nombre": "Conferencia de Tecnologia",
    "ubicacion": "Puerto Rico",
    "fecha_hora": "2025-06-15T09:00:00",
    "capacidad": 500,
    "descripcion": "Una conferencia sobre las ultimas tendencias en tecnologia"
}


