GET http://127.0.0.1:5000/info
Content-Type: application/json

POST http://127.0.0.1:5000/crear_usuario
Content-Type: application/json

GET http://127.0.0.1:5000/usuarios
Content-Type: application/json

